apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: print-date
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox:1.28
            command: ["sh","-c","date"] 
          restartPolicy: OnFailure