apiVersion: batch/v1
kind: Job
metadata:
  name: print-date
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox:1.28
        command: ["sh","-c","date"]
      restartPolicy: Never