apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: liveness
  name: liveness
spec:
  containers:
  - image: busybox:1.28
    name: liveness
    resources: {}
    command: ["sh","-c","touch /tmp/start.log && sleep 3600"]
    livenessProbe:
      exec:
        command: ["cat","/tmp/start.log"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}