apiVersion: batch/v1
kind: Job
metadata:
  name: multi-print-date
spec:
  completions: 20
  parallelism: 5
  template:
    spec:
      containers:
      - name: busybox
        image: busybox:1.28
        command: ["sh","-c","sleep 10 && date"]
      restartPolicy: Never