apiVersion: v1
kind: Pod
metadata:
  name: vk-pod
  namespace: voidking
spec:
  containers:
  - name: nginx
    image: nginx:1.16
    resources:
      requests:
        cpu: "250m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "128Mi"