apiVersion: v1
data:
  password: dmtwYXNzd29yZA==
  username: dm9pZGtpbmc=
kind: Secret
metadata:
  creationTimestamp: null
  name: vk-pod-secret
---
apiVersion: v1
kind: Pod
metadata:
  name: vk-pod
  labels:
    app: vk-pod
spec:
  containers:
  - name: vk-busybox
    image: busybox
    command: [ "/bin/sh", "-c", "env" ]
      env:
        # Define the environment variable
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              # name of secret
              name: vk-pod-secret
              # Specify the key associated with the value
              key: username
    volumeMounts:
    - name: mysecret
      mountPath: /secret
  volumes:
  - name: mysecret
    secret:
      secretName: vk-pod-secret