apiVersion: v1
kind: Pod
metadata:
  name: vk-pod
  labels:
    app: vk-pod
spec:
  containers:
  - name: vk-busybox
    image: busybox
    command: [ "/bin/sh", "-c", "env" ]
      env:
        # Define the environment variable
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              # name of secret
              name: vk-pod-secret
              # Specify the key associated with the value
              key: username
        # Define the environment variable
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              # name of secret
              name: vk-pod-secret
              # Specify the key associated with the value
              key: password