apiVersion: v1
kind: ConfigMap
metadata:
  name: vk-pod-configmap
  namespace: default
data:
  color: red
  textmode: "true"
---
apiVersion: v1
kind: Pod
metadata:
  name: vk-pod
  labels:
    app: vk-pod
spec:
  containers:
  - name: vk-busybox
    image: busybox
    command: [ "/bin/sh", "-c", "env" ]
      env:
        # Define the environment variable
        - name: COLOR
          valueFrom:
            configMapKeyRef:
              # name of configmap
              name: vk-pod-configmap
              # Specify the key associated with the value
              key: color