apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: voidking
spec:
  groups:
  - system:authenticated
  usages:
  - digital signature
  - key encipherment
  - server auth
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQTBSWHVUZnhzRDFVaHlVTUlGa1Y0aFVKZUV0QUQ2bzVFVnkzV1laU2JqejhyCmNBamRKVUlNZDV1TFdHb25FMzdoWWpwRnl4ckNzVTJKd2JyMlRTa3hJd3c1T3N6V0ZlS3AxN0RYZ3RUSjNBbXgKTkExQWx5dmMwVE03VlMxSDRpcEQxbXlBWFE3YXNKWVNCeFRKd0V5VHNnMlB6TXY0bHlicThqeVNWYXRlUFJRawpsZWlZWXFnSXdUSk1HakxRVGhOdW9BWlpiZ1lyLytydUZMQUdBWUg0UXRvRjVmNHFUUTFmTTN1ejVDS2xVb2t3CnpFcWdRUzV5eCs3M0xncSthT2xzYVAzWFhZQkdCV1dCeWFYRjhpMitSZkc0VEhCVm51L2R2Y0hiTmZ6cTY3OGEKZ0k3T1VjTnRDaE0rSHRBZkVkME95dGZnTzc1bFlvVEtRUTJMZjdaUlZRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBSk8vM2FkV2cvR0w5Z3lBaHdCZDluSzBzUFVBc0JhU3JIUHNud2pPNjlFbTVWYWRCekh2CjM2NXQzeUMwbWdiRmtZUFNFWWRsYkwzVk8vSGxOTmZGd1NQOGF4azh4M25ZZHNpdjN1U3BzbUY2NEkyYkphMnEKUDZkNDNmVGcrTjY2UGorQmRvQmRaUXhmY3Z4TUlYa3NwZGhwS1c3Umh3UTNuV1ZFTXNCZmFodmczdHRLNks1UApUeWNRSVp5SXgwTURxTTR3R2ppR2cyTVpGUzdQTTRWTHZjbGVoQTFIS1JkZVBCWnh3b092YWdOcEdYSmNEZDgzCmJmNXRjNitGeGJZQ29DaWt4VXBiVXBucU80NTJqVDZ4YUNkZFlkdkpJVS9HL3B6TjhnYU5lN092OWY3NUlWTFUKVFhJZzhGSnZzdjFZSE4zUUE1M0VBNmw5NVFxcjdXdndZRU09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=